-- Phase 2 Plan 3: fix audit trigger on aircraft_equipment
--
-- 02-01 mistakenly attached audit.fn_log_change() to public.aircraft_equipment,
-- but that table has a composite PK (aircraft_id, tag) and no `id` column —
-- audit.fn_log_change() resolves v_record_id via `NEW ->> 'id'` which yields
-- NULL, and audit_log.record_id is NOT NULL. Any INSERT into
-- aircraft_equipment via a normal user connection fails with:
--
--   null value in column "record_id" of relation "audit_log" violates not-null
--
-- aircraft_equipment is explicitly NOT training-record-relevant (per 02-01
-- key-decisions: "emergency_contact, info_release_authorization, and
-- aircraft_equipment get audit-only triggers (no hard-delete blocker) because
-- they are not training-record-relevant"), so the correct fix is to drop the
-- audit trigger. Plan 8 adds cost/audit reporting and can revisit whether
-- tag-churn needs its own history table (currently it does not).
--
-- This matches the 01-04 decision log: composite-PK tables do not participate
-- in audit_log until record_id is redesigned to accept composite keys.

drop trigger if exists aircraft_equipment_audit on public.aircraft_equipment;
